####################¿Cuantos accidentes ha habido en Madrid?

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT (SUM(?x) AS ?Total) WHERE {
 ?obs a qb:Observation ;
     mv:numberOfAccidents ?x
 
}

################Accidentes en Usera agrupados por tipo

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?tipo ?x WHERE {
 ?obs a qb:Observation ;
     mv:relatedDistrict "USERA" ;
     mv:numberOfAccidents ?x ;
     mv:hasAccidentType ?at .
  ?at skos:prefLabel ?tipo .
  FILTER ( lang(?tipo) = "es" ) 
 
}GROUP BY ?tipo


############# Accidentes de tipo colision multiple por distrito

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?dist ?x WHERE {
 ?obs a qb:Observation ;
     mv:relatedDistrict ?dist ;
     mv:numberOfAccidents ?x ;
     mv:hasAccidentType mv:MultipleCollision .
 
}GROUP BY ?dist

############# El distrito con mayor numero de accidentes de bicileta


prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?dist ?x WHERE {
 ?obs a qb:Observation ;
     mv:relatedDistrict ?dist ;
     mv:numberOfAccidents ?x ;
     mv:hasAccidentType mv:BicycleFall .
 
}GROUP BY ?dist
ORDER BY DESC(?x) LIMIT 3




