How many accidents were there in Madrid in 2013?

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix qb: <http://purl.org/linked-data/cube#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT (SUM(?x) AS ?total) WHERE {
?obs a qb:Observation ;
 mv:numberOfAccidents ?x .
}

------------------------------------------------------------------

Give me the number of accidents in Usera for each type of
accident

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix qb: <http://purl.org/linked-data/cube#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?tipo (?x AS ?total) WHERE {
?obs a qb:Observation ;
 mv:relatedDistrict "USERA" ;
 mv:numberOfAccidents ?x ;
 mv:hasAccidentType ?tipo .
} GROUP BY ?tipo

------------------------------------------------------------------

Give me the number of multiple collisions for each district

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix qb: <http://purl.org/linked-data/cube#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?distrito ?x WHERE {
?obs a qb:Observation ;
 mv:relatedDistrict ?distrito ;
 mv:numberOfAccidents ?x ;
 mv:hasAccidentType mv:MultipleCollision .

} GROUP BY ?distrito

------------------------------------------------------------------

Which is the district were the number of bicycle falls was
higher in 2013?

prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
prefix sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
prefix sdmx: <http://purl.org/linked-data/sdmx#> 
prefix mn: <http://example.org/resources/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix mv: <http://example.org/myVocabulary#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix qb: <http://purl.org/linked-data/cube#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?distrito ?x WHERE {
  ?obs a qb:Observation ;
  mv:relatedDistrict ?distrito ;
  mv:numberOfAccidents ?x ;
  mv:hasAccidentType mv:BicycleFall .
} ORDER BY DESC (?x)

------------------------------------------------------------------