language: php
dist: trusty

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

matrix:
    fast_finish: true
    include:
        - php: hhvm
    allow_failures:
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

sudo: true

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
    - composer require satooshi/php-coveralls:* --ignore-platform-reqs
    - travis_retry composer install --dev --no-interaction --ignore-platform-reqs

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_script: php vendor/bin/coveralls -v
