1
prefix myVocabulary: <http://example.org/myVocabulary#> 
prefix cube: <http://purl.org/linked-data/cube#>

SELECT DISTINCT SUM(?x) WHERE{?y a cube:Observation; myVocabulary:numberOfAccidents ?x.}

2
prefix myVocabulary: <http://example.org/myVocabulary#> 
prefix district: <http://example.org/myVocabulary#relatedDistrict>

SELECT DISTINCT * WHERE {?x district:'USERA'; myVocabulary:numberOfAccidents ?y.}

3
prefix myVocabulary: <http://example.org/myVocabulary#> 
prefix resources: <http://example.org/resources/>
prefix cube: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?x,?y where {?a a cube:Observation; myVocabulary:hasAccidentType myVocabulary:MultipleCollision; myVocabulary:relatedDistrict ?x; myVocabulary:numberOfAccidents ?y; cube:dataSet resources:MyDataset.}

4
prefix myVocabulary: <http://example.org/myVocabulary#> 
prefix cube: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?x,?y WHERE{?a a cube:Observation; myVocabulary:hasAccidentType myVocabulary:BicycleFall; myVocabulary:numberOfAccidents ?y; myVocabulary:relatedDistrict ?x.{SELECT DISTINCT(MAX(?b) AS ?y)WHERE{?a a cube:Observation; myVocabulary:relatedDistrict ?x; myVocabulary:numberOfAccidents ?b; myVocabulary:hasAccidentType myVocabulary:BicycleFall.}}}

5
prefix myVocabulary: <http://example.org/myVocabulary#> 
prefix cube: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?x,?y WHERE{{SELECT DISTINCT ?x SUM(xsd:int(?y)) AS ?y WHERE{?a a cube:Observation; myVocabulary:numberOfAccidents ?y; myVocabulary:relatedDistrict ?x.}}FILTER(?y>500)}