#SPARQL endpoint: http://sandbox.linkeddata.es/sparql
#Graph: http://sandbox.linkeddata.es/graph/accidentes

#1.How many accidents were there in Madrid in 2013?

SELECT SUM(?b) as ?Accidents WHERE {
	?obs a <http://purl.org/linked-data/cube#Observation>.
	?obs <http://example.org/instances#numberOfAccidents> ?b.
}

#2.Give me the number of accidents in Usera for each type of accident

SELECT ?Type ?Accidents WHERE {
	?obs a <http://purl.org/linked-data/cube#Observation>.
	?obs <http://example.org/instances#relatedDistrict> "USERA".
	?obs <http://example.org/instances#hasAccidentType> ?e.
	?e <http://www.w3.org/2004/02/skos/core#prefLabel> ?Type.
	?obs <http://example.org/instances#numberOfAccidents> ?Accidents.
	FILTER ( lang(?Type) = "es" ) 
}

#3.Give me the number of multiple collisions for each district

SELECT ?District ?Accidents WHERE {
	?obs a <http://purl.org/linked-data/cube#Observation>.
	?obs <http://example.org/instances#relatedDistrict> ?District.
	?obs <http://example.org/instances#hasAccidentType> <http://example.org/instances#MultipleCollision>.
	?obs <http://example.org/instances#numberOfAccidents> ?Accidents.
}
ORDER BY(?District)

#4.Which is the district were the number of bicycle falls was higher in 2013?

SELECT ?District max(?Accidents) as ?Accidents WHERE {
	?obs a <http://purl.org/linked-data/cube#Observation>.
	?obs <http://example.org/instances#relatedDistrict> ?District.
	?obs <http://example.org/instances#hasAccidentType> <http://example.org/instances#BicycleFall>.
	?obs <http://example.org/instances#numberOfAccidents> ?Accidents.
}
ORDER by desc(?Accidents)
LIMIT 1

#5.Give me the districts with more than 500 accidents in 2013

SELECT ?District ?Accidents WHERE {
	{
		SELECT distinct ?District (sum(xsd:double(?b)) as ?Accidents) WHERE {
			?obs a <http://purl.org/linked-data/cube#Observation>.
			?obs <http://example.org/instances#relatedDistrict> ?District.
			?obs <http://example.org/instances#numberOfAccidents> ?b.
		}
	} FILTER (?Accidents > 500)
} ORDER BY desc(?Accidents)
